sudo: required
services:
  - docker

before_install:
  - docker build -t node82/tacos -f Dockerfile .
  
language: generic

script:
  - docker run -e CI=true node82/tacos npm run test

deploy:
   provider: elasticbeanstalk
   region : "us-east-1"
   app: "dockedtacos"
   env: "taco-env"
   bucket_name: "elasticbeanstalk-us-east-1-298382983982"
   backet_path: "dockedtacos"
   on:
     branch: master

access_key_id: $AWS_ACCESS_KEY
secret_access_key: $AWS_SECRET_KEY
